  export const primaryFlagRules = {
    "en":
    {
      'Middle Africa': 'UK',
      'Eastern Africa': 'UK',
      'Western Africa': 'UK',
      'Southern Africa': 'UK',
      'Northern Africa': 'US',
      'South America': 'US',
      'Central America': 'US',
      'North America': 'US',
      'Australia and New Zealand': "AU" || "NZ",
      'Southern Asia': 'US',
      'Western Asia': 'US',
      'South-Eastern Asia': 'US',
      'Eastern Asia': 'US',
      'Central Asia': 'US',
      'Northern Europe': 'US',
      'Southeast Europe': 'US',
      'Southern Europe': 'US',
      'Central Europe': 'UK',
      'Western Europe': 'US',
      'Eastern Europe': 'UK',
      Caribbean: 'US',
      Melanesia: 'US',
      Micronesia: 'US',
      Polynesia: 'US'
    },
    "es" : {
      'Middle Africa': 'ES',
      'Eastern Africa': 'ES',
      'Western Africa': 'ES',
      'Southern Africa': 'MX',
      'Northern Africa': 'ES',
      'South America': "geolocation",
      'Central America': 'geolocation',
      'North America': 'MX',
      'Australia and New Zealand': 'ES',
      'Southern Asia': 'ES',
      'Western Asia': 'ES',
      'South-Eastern Asia': 'MX',
      'Eastern Asia': 'PE',
      'Central Asia': 'CO',
       Caribbean: 'DR',
      'Northern Europe': 'ES',
      'Southeast Europe': 'ES',
      'Southern Europe': 'ES',
      'Central Europe': 'ES',
      'Western Europe': 'ES',
      'Eastern Europe': 'ES',
      Melanesia: 'ES',
      Micronesia: 'ES',
      Polynesia: 'ES'
    },
    "fr": {
      'Middle Africa': 'FR',
      'Eastern Africa': 'FR',
      'Western Africa': 'FR',
      'Southern Africa': 'FR',
      'Northern Africa': 'FR',
      'South America': 'CA',
      'Central America': 'CA',
      'North America': 'CA',
      'Australia and New Zealand': 'CA',
      'Southern Asia': 'CA',
      'Western Asia': 'FR',
      'South-Eastern Asia': 'FR',
      'Eastern Asia': 'CA',
      'Central Asia': 'FR',
      Caribbean: 'FR',
      'Northern Europe': 'FR',
      'Southeast Europe': 'FR',
      'Southern Europe': 'FR',
      'Central Europe': 'FR',
      'Western Europe': 'FR',
      'Eastern Europe': 'FR',
      Melanesia: 'FR',
      Micronesia: 'FR',
      Polynesia: 'FR'
    },
    "it" : {All: "IT"},
    "pt" : {
      'Middle Africa': 'PT',
      'Eastern Africa': 'PT',
      'Western Africa': 'PT',
      'Southern Africa': 'PT',
      'Northern Africa': 'PT',
      'South America': 'BR',
      'Central America': 'BR',
      'North America': 'BR',
      'Australia and New Zealand': 'PT',
      'Southern Asia': 'BR',
      'Western Asia': 'PT',
      'South-Eastern Asia': 'PT',
      'Eastern Asia': 'BR',
      'Central Asia': 'PT',
      Caribbean: 'BR',
      'Northern Europe': 'PT',
      'Southeast Europe': 'PT',
      'Southern Europe': 'PT',
      'Central Europe': 'PT',
      'Western Europe': 'PT',
      'Eastern Europe': 'PT',
      Melanesia: 'BR',
      Micronesia: 'BR',
      Polynesia: 'BR'
    },
    "jp": {all: 'JP'},
    "ko": {all: 'KR'},
    "zh": {all: 'CN'},
    'hi': {all: 'IN'},
  }
