name = "mint-controller-pkp"
compatibility_date = "2023-07-31"
main = "./dist/worker.js"

[build]
command = "npm run build"

compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]
