name = "session-time-tracker"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2024-04-04"
[durable_objects]
bindings = [
{ name = "TIMER", class_name = "TimerObject" },
{name = "SESSION_STATE", class_name = "SessionState"},
{name = "DISCONNECTION_MANAGER", class_name = "DisconnectionManager"}
]

[[migrations]]
tag = "v3"
deleted_classes = ["WebSocketWorker"]
new_classes= ["SessionState"]
