name = "session-time-tracker"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[durable_objects]
bindings = [
{name = "SESSION_MANAGER", class_name = "SessionManager"},
]

[[migrations]]
tag = "v3"
deleted_classes = ["WebSocketWorker"]
new_classes= ["SessionState"]

[[migrations]]
tag = "v4"
new_classes = ["DisconnectionManager"]

[[migrations]]
tag = "v5"
deleted_classes= ["TimerObject", "DisconnectionManager"]
new_classes = ["ConnectionManager", "SessionTimer"]

[[migrations ]]
tag= "v6"
deleted_classes= ["SessionTimer", "SessionState", "ConnectionManager", "TimerObject", "DisconnectionManager"]
new_classes= ["WebSocketManager"]

[[migrations ]]
tag="v7"
deleted_classes=["WebSocketManager"]
new_classes=["SessionManager"]
