name = "session-time-tracker"
workers_dev = false
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
routes = [ { pattern = "session-time-tracker.charli.chat", custom_domain = true } ]

[durable_objects]
bindings = [
  { name = "SESSION_MANAGER", class_name = "SessionManager" },
  { name = "CONNECTION_MANAGER", class_name = "ConnectionManager" },
  { name = "SESSION_TIMER", class_name = "SessionTimer" },
  { name = "MESSAGE_RELAY", class_name = "MessageRelay" }
]

[[migrations]]
tag = "v1"
new_classes = ["SessionManager"]

[[migrations]]
tag = "v2"
new_classes = ["ConnectionManager", "SessionTimer", "MessageRelay"]

