name = "session-time-tracker-test"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
{ name = "SESSION_MANAGER", class_name = "SessionManager" },
{ name = "CONNECTION_MANAGER", class_name = "ConnectionManager" },
{ name = "SESSION_TIMER", class_name = "SessionTimer" },
{ name = "MESSAGE_RELAY", class_name = "MessageRelay" }
]

[[migrations]]
tag = "v1"
new_classes = ["SessionManager", "ConnectionManager", "SessionTimer", "MessageRelay"]
